export enum Action_Type {
  ADD_NEW_TODO = "ADD_NEW_TODO",
  DELETE_TODO = "DELETE_TODO",
  UPDATE_TODO = "UPDATE_TODO",
  SEARCH_TODO = "SEARCH_TODO",
  DELETE_LIST_CHECK_TODO = "DELETE_LIST_CHECK_TODO",
  UPDATE_ACTIVE_ID = "UPDATE_ACTIVE_ID",
  ADD_CHECK_TODO = "ADD_CHECK_TODO",
  DELETE_CHECK_TODO = "DELETE_CHECK_TODO",
}
